# Generated by Django 4.0.3 on 2022-04-06 11:19

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_brand_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('car_model', models.CharField(max_length=50, null=True)),
                ('first_reg', models.DateField(null=True)),
                ('odometer', models.IntegerField(null=True, validators=[common.validators.odometer_max_value])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_brand_api.carbrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
